create warehouse PRJ10_WH;
USE WAREHOUSE PRJ10_WH;
CREATE OR REPLACE DATABASE prj11_DW;
CREATE OR REPLACE SCHEMA prj11_dw.mdm;
use database prj11_dw;
USE SCHEMA prj11_dw.MDM;

create or replace file format csv_load_format
type='csv'
field_delimiter=','
skip_header=1
null_if=('NULL','null','')
field_optionally_enclosed_by='"';

create or replace stage mdm_stage
file_format=csv_load_format;

CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID   INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY          VARCHAR(100),
    STATE         VARCHAR(100),
    MEMBERSHIP    VARCHAR(50),
    SEGMENT       VARCHAR(50)
);

CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID    INT,
    CUSTOMER_NAME  VARCHAR(100),
    CITY           VARCHAR(100),
    STATE          VARCHAR(100),
    MEMBERSHIP     VARCHAR(50),
    SEGMENT        VARCHAR(50),
    EFFECTIVE_DATE DATE
);

COPY INTO STG_CUSTOMERS_INITIAL
FROM @MDM_STAGE/customers_initial.csv;

COPY INTO STG_CUSTOMER_UPDATES
FROM @MDM_STAGE/customer_updates.csv;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY          INT AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_ID           INT,
    CUSTOMER_NAME         VARCHAR(100),
    CITY                  VARCHAR(100),
    PREVIOUS_CITY         VARCHAR(100),
    STATE                 VARCHAR(100),
    CURRENT_MEMBERSHIP    VARCHAR(50),
    PREVIOUS_MEMBERSHIP   VARCHAR(50),
    HISTORICAL_MEMBERSHIP VARCHAR(50),
    SEGMENT               VARCHAR(50),
    EFFECTIVE_DATE        DATE,
    EXPIRY_DATE           DATE,
    IS_CURRENT            BOOLEAN
);

INSERT INTO DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    NULL AS PREVIOUS_CITY,
    STATE,
    MEMBERSHIP AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    SEGMENT,
    '2026-01-01'::DATE AS EFFECTIVE_DATE,
    '9999-12-31'::DATE AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM STG_CUSTOMERS_INITIAL;

UPDATE DIM_CUSTOMER d
SET 
    EXPIRY_DATE = u.EFFECTIVE_DATE - 1,
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE
  AND u.CUSTOMER_ID = 101;

  UPDATE DIM_CUSTOMER d
SET 
    EXPIRY_DATE = u.EFFECTIVE_DATE - 1,
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE
  AND u.CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER d
SET 
    EXPIRY_DATE = u.EFFECTIVE_DATE - 1,
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE
  AND u.CUSTOMER_ID = 104;

INSERT INTO DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT 
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,
    u.CITY,
    d.CITY AS PREVIOUS_CITY,
    u.STATE,
    u.MEMBERSHIP AS CURRENT_MEMBERSHIP,
    d.HISTORICAL_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,
    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE,
    '9999-12-31'::DATE AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM STG_CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER d 
  ON u.CUSTOMER_ID = d.CUSTOMER_ID
WHERE d.EXPIRY_DATE = u.EFFECTIVE_DATE - 1;

---Synchronize global current & prior attributes across all records
UPDATE DIM_CUSTOMER d
SET 
    CITY = u.CITY,
    PREVIOUS_CITY = CASE WHEN d.CITY <> u.CITY THEN d.CITY ELSE d.PREVIOUS_CITY END,
    STATE = u.STATE,
    CURRENT_MEMBERSHIP = u.MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = d.HISTORICAL_MEMBERSHIP
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
AND u.CUSTOMER_ID = 101;

UPDATE DIM_CUSTOMER d
SET 
    CITY = u.CITY,
    PREVIOUS_CITY = CASE WHEN d.CITY <> u.CITY THEN d.CITY ELSE d.PREVIOUS_CITY END,
    STATE = u.STATE,
    CURRENT_MEMBERSHIP = u.MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = d.HISTORICAL_MEMBERSHIP
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND u.CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER d
SET 
    CITY = u.CITY,
    PREVIOUS_CITY = CASE WHEN d.CITY <> u.CITY THEN d.CITY ELSE d.PREVIOUS_CITY END,
    STATE = u.STATE,
    CURRENT_MEMBERSHIP = u.MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = d.HISTORICAL_MEMBERSHIP
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
AND u.CUSTOMER_ID = 104;

SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101
  AND '2026-03-15'::DATE BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT 'TOTAL RECORD COUNT' AS METRIC, COUNT(*) AS VALUE FROM DIM_CUSTOMER
UNION ALL
SELECT 'CURRENT RECORD COUNT' AS METRIC, COUNT(*) AS VALUE FROM DIM_CUSTOMER WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'HISTORICAL RECORD COUNT' AS METRIC, COUNT(*) AS VALUE FROM DIM_CUSTOMER WHERE IS_CURRENT = FALSE;