
-- TASK 1: Create Warehouse, Database, and Schema Context

CREATE OR REPLACE WAREHOUSE COMPUTE_WH 
WITH 
    WAREHOUSE_SIZE = 'X-SMALL' 
    AUTO_SUSPEND = 300 
    AUTO_RESUME = TRUE 
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE p_12;
CREATE OR REPLACE SCHEMA SALES_ANALYTICS;
USE SCHEMA p_12.SALES_ANALYTICS;



-- TASK 2: Create Store Conformed Dimension Table (DIM_STORE)

CREATE OR REPLACE TABLE DIM_STORE (
    STORE_KEY     NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    STORE_ID      NUMBER,
    STORE_NAME    VARCHAR(100),
    CITY          VARCHAR(50),
    STATE         VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);



-- TASK 3: Create Product Dimension Table (DIM_PRODUCT)
 
CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY  NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    PRODUCT_ID   NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY     VARCHAR(50),
    UNIT_PRICE   NUMBER(10, 2)
);


-- TASK 4: Create Hybrid Customer Dimension Table (DIM_CUSTOMER_HYBRID)
CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY          NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    CUSTOMER_ID           NUMBER,
    CUSTOMER_NAME         VARCHAR(100),
    CITY                  VARCHAR(50),
    PREVIOUS_CITY         VARCHAR(50),
    STATE                 VARCHAR(50),
    CURRENT_MEMBERSHIP    VARCHAR(30),
    PREVIOUS_MEMBERSHIP   VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT               VARCHAR(30),
    EFFECTIVE_DATE        DATE,
    EXPIRY_DATE           DATE,
    IS_CURRENT            BOOLEAN
);


-- TASK 5: Populate Initial Store and Product Dimension Data
INSERT INTO DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, STORE_MANAGER) VALUES
(201, 'Metro Flagship', 'Hyderabad', 'Telangana', 'Rajesh Kumar'),
(202, 'Express Hub', 'Warangal', 'Telangana', 'Sita Sharma'),
(203, 'Coastal Center', 'Vijayawada', 'Andhra Pradesh', 'Vikram Rao');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE) VALUES
(501, 'Laptop Pro', 'Electronics', 75000.00),
(502, 'Wireless Mouse', 'Electronics', 1500.00),
(503, 'Ergonomic Chair', 'Furniture', 12000.00),
(504, 'Coffee Maker', 'Appliances', 4500.00);


-- TASK 6: Populate Initial Customer Dimension Data
INSERT INTO DIM_CUSTOMER_HYBRID (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
) VALUES
(101, 'Amit Sharma', 'Hyderabad', NULL, 'Telangana', 'Silver', NULL, 'Silver', 'Regular', '2026-01-01', '9999-12-31', TRUE),
(102, 'Priya Reddy', 'Warangal', NULL, 'Telangana', 'Gold', NULL, 'Gold', 'Premium', '2026-01-01', '9999-12-31', TRUE),
(103, 'Rahul Verma', 'Vijayawada', NULL, 'Andhra Pradesh', 'Silver', NULL, 'Silver', 'Regular', '2026-01-01', '9999-12-31', TRUE),
(104, 'Neha Patel', 'Hyderabad', NULL, 'Telangana', 'Gold', NULL, 'Gold', 'Premium', '2026-01-01', '9999-12-31', TRUE),
(105, 'Arjun Gupta', 'Nagpur', NULL, 'Maharashtra', 'Bronze', NULL, 'Bronze', 'Regular', '2026-01-01', '9999-12-31', TRUE);


-- TASK 7: Create Sales Transaction Fact Table (FACT_SALES)
CREATE OR REPLACE TABLE FACT_SALES (
    SALES_KEY        NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    TRANSACTION_ID   VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_KEY     NUMBER REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),
    STORE_KEY        NUMBER REFERENCES DIM_STORE(STORE_KEY),
    PRODUCT_KEY      NUMBER REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    QUANTITY         NUMBER,
    UNIT_PRICE       NUMBER(10, 2),
    TOTAL_AMOUNT     NUMBER(12, 2)
);


-- TASK 8: Insert Q1 2026 Sales Fact Transactions
INSERT INTO FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT 
    'TXN-1001',
    '2026-02-15'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    1,
    p.UNIT_PRICE,
    (1 * p.UNIT_PRICE)
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s ON s.STORE_ID = 201
JOIN DIM_PRODUCT p ON p.PRODUCT_ID = 501
WHERE c.CUSTOMER_ID = 101 AND c.IS_CURRENT = TRUE;

INSERT INTO FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT 
    'TXN-1002',
    '2026-03-10'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    2,
    p.UNIT_PRICE,
    (2 * p.UNIT_PRICE)
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s ON s.STORE_ID = 203
JOIN DIM_PRODUCT p ON p.PRODUCT_ID = 502
WHERE c.CUSTOMER_ID = 103 AND c.IS_CURRENT = TRUE;


-- TASK 9: Apply Store Manager Update (SCD Type 1 Overwrite)
UPDATE DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;

SELECT 
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    STORE_MANAGER
FROM DIM_STORE
WHERE STORE_ID = 201;


-- TASK 10: Execute Multi-Attribute Customer Updates
CREATE OR REPLACE TEMPORARY TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID    NUMBER,
    CUSTOMER_NAME  VARCHAR(100),
    CITY           VARCHAR(50),
    STATE          VARCHAR(50),
    MEMBERSHIP     VARCHAR(30),
    SEGMENT        VARCHAR(30),
    EFFECTIVE_DATE DATE
);

INSERT INTO STG_CUSTOMER_UPDATES VALUES
(101, 'Amit Sharma', 'Bengaluru', 'Karnataka', 'Gold', 'Premium', '2026-04-01'),
(103, 'Rahul Verma', 'Chennai', 'Tamil Nadu', 'Gold', 'Premium', '2026-04-05'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Platinum', 'Premium', '2026-04-10');

-- Step 1: Expire active records for Customers 101, 103, and 104
UPDATE DIM_CUSTOMER_HYBRID d
SET 
    EXPIRY_DATE = u.EFFECTIVE_DATE - 1,
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE
  AND u.CUSTOMER_ID = 101;

UPDATE DIM_CUSTOMER_HYBRID d
SET 
    EXPIRY_DATE = u.EFFECTIVE_DATE - 1,
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE
  AND u.CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_HYBRID d
SET 
    EXPIRY_DATE = u.EFFECTIVE_DATE - 1,
    IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE
  AND u.CUSTOMER_ID = 104;

-- Step 2: Insert new active row versions
INSERT INTO DIM_CUSTOMER_HYBRID (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT 
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,
    u.CITY,
    d.CITY AS PREVIOUS_CITY,
    u.STATE,
    u.MEMBERSHIP AS CURRENT_MEMBERSHIP,
    d.HISTORICAL_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,
    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE,
    '9999-12-31'::DATE AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM STG_CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_HYBRID d 
  ON u.CUSTOMER_ID = d.CUSTOMER_ID
WHERE d.EXPIRY_DATE = u.EFFECTIVE_DATE - 1;

-- Step 3: Synchronize global profile attributes across all historical records
UPDATE DIM_CUSTOMER_HYBRID d
SET 
    CITY = u.CITY,
    PREVIOUS_CITY = CASE WHEN d.CITY <> u.CITY THEN d.CITY ELSE d.PREVIOUS_CITY END,
    STATE = u.STATE,
    CURRENT_MEMBERSHIP = u.MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = d.HISTORICAL_MEMBERSHIP
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND u.CUSTOMER_ID = 101;

UPDATE DIM_CUSTOMER_HYBRID d
SET 
    CITY = u.CITY,
    PREVIOUS_CITY = CASE WHEN d.CITY <> u.CITY THEN d.CITY ELSE d.PREVIOUS_CITY END,
    STATE = u.STATE,
    CURRENT_MEMBERSHIP = u.MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = d.HISTORICAL_MEMBERSHIP
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND u.CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_HYBRID d
SET 
    CITY = u.CITY,
    PREVIOUS_CITY = CASE WHEN d.CITY <> u.CITY THEN d.CITY ELSE d.PREVIOUS_CITY END,
    STATE = u.STATE,
    CURRENT_MEMBERSHIP = u.MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = d.HISTORICAL_MEMBERSHIP
FROM STG_CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND u.CUSTOMER_ID = 104;


-- TASK 11: Insert Q2 2026 Sales Transaction
INSERT INTO FACT_SALES (
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_KEY,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT
)
SELECT 
    'TXN-2001',
    '2026-04-15'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    1,
    p.UNIT_PRICE,
    (1 * p.UNIT_PRICE)
FROM DIM_CUSTOMER_HYBRID c
JOIN DIM_STORE s ON s.STORE_ID = 201
JOIN DIM_PRODUCT p ON p.PRODUCT_ID = 503
WHERE c.CUSTOMER_ID = 101 AND c.IS_CURRENT = TRUE;


-- TASK 12: Display Full Customer Dimension History
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


-- TASK 13: Point-in-Time Point-of-Sale Analytics Query
SELECT 
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY AS CURRENT_CITY,
    c.HISTORICAL_MEMBERSHIP AS MEMBERSHIP_AT_PURCHASE,
    c.SEGMENT AS SEGMENT_AT_PURCHASE,
    s.STORE_NAME,
    p.PRODUCT_NAME,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
JOIN DIM_CUSTOMER_HYBRID c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_STORE s ON f.STORE_KEY = s.STORE_KEY
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
WHERE c.CUSTOMER_ID = 101
ORDER BY f.TRANSACTION_DATE;


-- TASK 14: Warehouse Record Count and Data Auditing Validation
SELECT 'STORE DIMENSION RECORDS' AS METRIC, COUNT(*) AS VALUE FROM DIM_STORE
UNION ALL
SELECT 'PRODUCT DIMENSION RECORDS' AS METRIC, COUNT(*) AS VALUE FROM DIM_PRODUCT
UNION ALL
SELECT 'TOTAL CUSTOMER DIMENSION RECORDS' AS METRIC, COUNT(*) AS VALUE FROM DIM_CUSTOMER_HYBRID
UNION ALL
SELECT 'CURRENT CUSTOMER RECORDS' AS METRIC, COUNT(*) AS VALUE FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'HISTORICAL CUSTOMER RECORDS' AS METRIC, COUNT(*) AS VALUE FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = FALSE
UNION ALL
SELECT 'FACT SALES TRANSACTIONS' AS METRIC, COUNT(*) AS VALUE FROM FACT_SALES;